version: "2.2"
services:
  http_proxy:
    build:
      context: .
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
  redis:
    image: "redis:6"
    ports:
      - "13138:6379"
  test:
    build:
      context: .
    command: bash -c "cd /usr/src/app/src && python -m unittest discover ../tests/"
